###
### N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
###

@host = localhost:8443

### Suche Modell und Art von allen Autos
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  autos {
    modell
    art
  }
}

### Suche modell, art und seriennr von einem Auto mit vorhandener Auto-ID
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  auto(id: "00000000-0000-0000-0000-000000000001") {
    modell
    art
    seriennr
  }
}

### Suche modell und art von Autos mit vorhandenem Modell
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  autos(modell: "Alpha") {
    modell
    art
  }
}


### Suche modell, art und assistenzsysteme von Autos mit vorhandenem Modell
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  autos(modell: "a") {
    modell
    art
    assistenzsysteme
  }
}

### Neues Auto anlegen
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  createAuto(
    modell: "Test"
    rating: 1
    art: "AUTOMATIK"
    hersteller: "VW_HERSTELLER"
    preis: 11000.1
    premium: 0.011
    lieferbar: true
    datum: null
    seriennr: "3-89722-583-2"
    homepage: "http://test.de"
    assistenzsysteme: ["TEMPOMAT"]
  ) {
    _id
  }
}

### Vorhandenes Auto aktualisieren
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  updateAuto(
    _id: "00000000-0000-0000-0000-000000000003",
    modell: "Geaendert",
    rating: 5,
    art: "AUTOMATIK",
    hersteller: "PORSCHE_HERSTELLER",
    preis: 99000.99,
    premium: 0.099,
    lieferbar: false,
    datum: "2018-01-31",
    seriennr: "3-8273-1552-2",
    homepage: "https://test.te",
    assistenzsysteme: [
      "AUTOPILOT",
      "TEMPOMAT"
    ],
    version: 0
  ) {
    version
  }
}

### Vorhandenes Auto loeschen
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  deleteAuto(id: "00000000-0000-0000-0000-000000000004")
}
