###
### N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
###

### Localhost
// @host = localhost:8443
### Heroku
@host = boiling-fjord-85923.herokuapp.com

### Suche alle Hersteller
https://{{host}}/hersteller
